/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaEscolha;

public class App {

    public static void main(String[] args) {
        
        int codigoProduto = 2;
        
        switch(codigoProduto) {
            
            case 1:
                
                break;
                
            case 2:
                
                break;
                
            default:

        }
    }
}
