/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaCondicionalSe;

public class App {

    public static void main(String[] args) {

        int media = 7;

        if (media >= 7) {            
            if (media == 10) {
                //APROVADO COM NOTA MAXIMA
            } else {
                //APROVADO
            }
        } else {
            //REPROVADO
        }

    }
}
