/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VariaveisTiposOperadores;

public class App {

    public static void main(String[] args) {
        
        int idade = 20;
        float cotacaoDolar = 5.0f;
        double cotacaoEuro = 6.0d;
        char genero = 'M';
        byte pontos = 0;
        boolean estaCadastrado = false;
        
        String nome = "Esse é um texto de uma variável String";
    }
}
