/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        // Comentário de linha
        
        /* 
            Comentário
            de 
            bloco
        */
        
        /** 
         * Comentário
         * de
         * documentação
        */
        
        System.out.println("Olá mundo!");
        System.out.println("Meu segundo comando de saída!");
        
        Scanner leitor = new Scanner(System.in);
        
        int idade = leitor.nextInt();
        float cotacaoDolar = leitor.nextFloat();
        double cotacaoEuro = leitor.nextDouble();
        String nome = leitor.nextLine();
        String codigoRua = leitor.next();
        
        System.out.print("Texto que será exibido no console.");
        System.out.println("Texto que será exibido no console.");

    }
}
